version: '2'

services:

  fpm:
    image: natansdj/fpm-bedrock-wp
    # build: ./fpm-wordpress
    container_name: elbow_fpm
    external_links:
      - dev_mariadb:mariadb
    volumes:
      #- /var/www/html
      - ../_htdocs/genstudio_elbow_wp:/var/www/html
      - .:/home/bedrock
    # ports:
    #   - "9000:9000"
    environment:
      DB_NAME: dev_elbow_wp
      DB_USER: vti
      DB_PASSWORD: vti
      DB_HOST: mariadb
      WP_ENV: development
      WP_HOME: http://elbow-wp.genstudio.vm
      WP_SITEURL: http://elbow-wp.genstudio.vm/wp
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      PHP_IDE_CONFIG: serverName=elbow-wp.genstudio.vm
      XDEBUG_CONFIG: remote_host=172.18.0.1 remote_connect_back=1 remote_autostart=1 profiler_enable_trigger=1 idekey=PHPSTORM
      # uncomment below for new installations
      #ADMIN_USER: admin
      #ADMIN_PASS: admin
      #ADMIN_EMAIL: admin@asd.com
      #SITE_TITLE: WordPress

  nginx:
    image: natansdj/nginx-bedrock-wp
    # build: ./nginx-wordpress
    container_name: elbow_nginx
    links:
      - fpm:fpm
    volumes_from:
      - fpm
    # ports:
    #   - "8000:80"
    environment:
#      uncomment below to remove installation password
      ALLOW_INSTALL: "yes"
      VIRTUAL_HOST: "elbow-wp.genstudio.vm"
      VIRTUAL_PORT: "80"

  # wpcli:
  #   image: tatemz/wp-cli
  #   container_name: elbow_cli
  #   volumes:
  #     - /home/www/wordpress:/var/www/html
  #   volumes_from:
  #     - storage
  #     # - fpm
  #   # ports:
  #   #   - "8080:80"
  #   external_links:
  #     - dev_mariadb:mariadb
  #   # entrypoint: wp
  #   # command: "--info"
  #   environment:
  #     VIRTUAL_HOST: "wordpress.vm"
  #     VIRTUAL_PORT: "80"
  #     WORDPRESS_DB_HOST: mariadb
  #     WORDPRESS_DB_NAME: dev_wordpress
  #     WORDPRESS_DB_USER: vti
  #     WORDPRESS_DB_PASSWORD: vti
  #     WORDPRESS_TABLE_PREFIX: wp_

  # storage:
  #   build:
  #     context: storage/
  #   volumes:
  #     - /storage

volumes:
  wordpress-db:
    driver: local
  # storage:
  #   driver: local
  #   driver_opts:
  #     device: /home/vt745/Documents/bedrock/backup
  #     o: bind

networks:
  default:
    external:
      name: dev
