version: '2'

services:
  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vti-sixmurs-int
    volumes:
#      - wordpress-db:/var/lib/mysql
      - /mnt/sda1/mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"

  fpm:
    image: iamdb/fpm-bedrock-wordpress
    container_name: fpm
    links:
      - mariadb:mariadb
    volumes:
      #- /var/www/html
      #- /mnt/docker/bedrock/data:/var/www/html
      - /c/Users/vti745/Documents/Kitematic/htdocs/php_wp_sixmurs_int:/var/www/html
      - .:/home/bedrock
    ports:
      - "9000:9000"
    environment:
      DB_NAME: vti-sixmurs-int
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mariadb
      WP_ENV: development
      WP_HOME: http://internal.sixmurs.dev
      WP_SITEURL: http://internal.sixmurs.dev/wp
      # uncomment below for new installations
      #ADMIN_USER: admin
      #ADMIN_PASS: admin
      #ADMIN_EMAIL: admin@asd.com
      #SITE_TITLE: WordPress

  nginx:
    image: iamdb/nginx-bedrock-wordpress
    container_name: nginx
    links:
      - fpm:fpm
    volumes_from:
      - fpm
    ports:
      - "80:80"
    environment:
#      uncomment below to remove installation password
      ALLOW_INSTALL: "yes"

  adminer:
    image: hardware/adminer
    container_name: adminer
    links:
      - mariadb:mariadb
    ports:
      - "8888:8888"

volumes:
  wordpress-db:
    driver: local
