version: '2'

services:
  mariadb:
    image: mariadb:10.1
    container_name: bedrock_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vti-sixmurs-int
    volumes:
#      - wordpress-db:/var/lib/mysql
      - /mnt/sda1/mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"

  fpm:
    # image: iamdb/fpm-bedrock-wordpress
    build: ./fpm-wordpress
    container_name: bedrock_fpm
    links:
      - mariadb:mariadb
    volumes:
      #- /var/www/html
      #- /mnt/docker/bedrock/data:/var/www/html
      - ../_htdocs/php_wp_sixmurs_int:/var/www/html
      - .:/home/bedrock
    ports:
      - "9000:9000"
    environment:
      DB_NAME: vti-sixmurs-int
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mariadb
      WP_ENV: development
      WP_HOME: http://internal.sixmurs.dev
      WP_SITEURL: http://internal.sixmurs.dev/wp
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      XDEBUG_CONFIG: remote_host=localhost
      # uncomment below for new installations
      #ADMIN_USER: admin
      #ADMIN_PASS: admin
      #ADMIN_EMAIL: admin@asd.com
      #SITE_TITLE: WordPress

  nginx:
    # image: iamdb/nginx-bedrock-wordpress
    build: ./nginx-wordpress
    container_name: bedrock_nginx
    links:
      - fpm:fpm
    volumes_from:
      - fpm
    ports:
      - "80:80"
    environment:
#      uncomment below to remove installation password
      ALLOW_INSTALL: "yes"

  adminer:
    image: hardware/adminer
    container_name: bedrock_adminer
    links:
      - mariadb:mariadb
    ports:
      - "8888:8888"

  caldav:
    volumes:
      - ../_htdocs/caldav-api:/var/www
      - ../_htdocs/caldav-api/conf:/etc/nginx/sites-available
    image: igez/nginx-php7.0-fpm
    ports:
      - "8080:80"
    restart: always
    container_name: bedrock_caldav
    environment:
      - PUBLIC=public
    links:
      - mariadb

volumes:
  wordpress-db:
    driver: local
