adminer:
  image: hardware/adminer
  container_name: adminer
  links:
    - mariadb:mariadb
  ports:
    - "8888:8888"

mariadb:
  image: mariadb:10.1
  container_name: mariadb
  volumes:
    - /mnt/docker/mysql/db:/var/lib/mysql
    #- /c/Users/vti745/Documents/Kitematic/mariadb/var/lib/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
  ports:
    - "3306:3306"
